# Generated by Django 5.2.10 on 2026-01-10 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
        ("products", "0001_initial"),
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="cartinorder",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="cartpayment",
            name="order_cart",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="orders.cartinorder"
            ),
        ),
        migrations.AddField(
            model_name="cartpayment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="orders",
            name="address",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.addresses"
            ),
        ),
        migrations.AddField(
            model_name="orders",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="products.products"
            ),
        ),
        migrations.AddField(
            model_name="orders",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="cartinorder",
            name="orders_in",
            field=models.ManyToManyField(to="orders.orders"),
        ),
        migrations.AddField(
            model_name="payment",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="orders.orders"
            ),
        ),
        migrations.AddField(
            model_name="orders",
            name="payment_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="orders.payment",
            ),
        ),
    ]
